### DISCUSSION TITLE
Package acceptance validation error: The uploaded package consists of a compressed file.

### DISCUSSION THREAD

**Discussion by aiktb** [microsoft/MicrosoftEdge-Extensions#135] [Q&A]
> [!CAUTION]
> The following checks failed:Package acceptance validation error: The uploaded package consists of a compressed file. Please remove the file and try uploading the package again.

![image](https://github.com/microsoft/MicrosoftEdge-Extensions/assets/104723527/f1919a0d-99be-407a-8f6e-57c3143d8263)

What's going on? What should I do to successfully submit my extension?
I can't submit my extension to Microsoft Edge, is it because of these `*.dat.gz` files? But my previous submitted versions also contained these files and could be submitted successfully.

```
chrome-mv3-prod.zip
│  core.790498ea.js
│  customSelector.c9a39b24.js
│  dm-sans-bold.d914fe0b.woff2
│  dm-sans-regular.7697eaed.woff2
│  eventHandler.4c7ab9ec.js
│  furiganaMaker.ade415dd.js
│  icon128.plasmo.b6713b7b.png
│  icon16.plasmo.afe082d6.png
│  icon32.plasmo.fd808d76.png
│  icon48.plasmo.9be659db.png
│  icon64.plasmo.6561f8f6.png
│  jetbrains-mono-bold.945d4fa0.woff2
│  jetbrains-mono-regular.85a43e25.woff2
│  manifest.json
│  options.38812c9a.js
│  options.html
│  pageMarker.b609a3a5.js
│  popup.43e00584.js
│  popup.822fe94d.css
│  popup.html
│
├─assets
│  └─dicts
│          base.dat.gz
│          cc.dat.gz
│          check.dat.gz
│          tid.dat.gz
│          tid_map.dat.gz
│          tid_pos.dat.gz
│          unk.dat.gz
│          unk_char.dat.gz
│          unk_compat.dat.gz
│          unk_invoke.dat.gz
│          unk_map.dat.gz
│          unk_pos.dat.gz
│
└─static
    └─background
            index.js
```

**Comment by aiktb** [comment]
When I delete these *.dat.gz files, the submission can be successful.
The problem is that the library I'm using relies on this file format and unpacking it will break my extension. 😅
I successfully submitted these files a month ago, what happened to make Microsoft change this?
Note that both Firefox and Chrome accept these *.dat.gz files, Edge is frustrating me.

**Reply by VladislavAntonyuk** [reply]
I can add, that removing all .gz files solves the issue

**Comment by aiktb** [comment]
Another horrible thing I've discovered is that the Chrome Web Store can't upload zip packages containing more than 10MB of files, and I'm using files that exceed that limit, which will result in me needing to maintain multiple versions of the expansion packages.

Damn! If Edge can't revert back to the old rule of letting me upload zips containing compressed files, I may drop my support for Edge as it greatly increases my maintenance costs.

There is no value in censoring these binaries, they just need to be loaded into memory when necessary, keeping them in their original compressed form is beneficial and I don't see why Edge would do that.

**Comment by ManikanthMSFT** [comment]
Hey @aiktb, Sorry for the delay and please note that we have sent your query to our team for further confirmation and once we hear from them, we will write back to you.

**Reply by aiktb** [reply]
> Hey @aiktb, Sorry for the delay and please note that we have sent your query to our team for further confirmation and once we hear from them, we will write back to you.

Hi,
Additional information: I found that Microsoft Partner only checks the file suffix, and changing the file name can bypass this restriction, so I think this restriction is meaningless.

**Reply by ManikanthMSFT** [reply]
Hey @aiktb, could you please confirm are you still getting the package acceptance validation error while uploading the package?

**Reply by aiktb** [reply]
> Hey @aiktb, could you please confirm are you still getting the package acceptance validation error while uploading the package?

I confirmed that this error still exists. The corresponding zip can be built from https://github.com/aiktb/FuriganaMaker/tree/v2.1.5 by following the steps below:
```bash
nvm use
pnpm install
pnpm zip
```

**Reply by aiktb** [reply]
> Hey @aiktb, could you please confirm are you still getting the package acceptance validation error while uploading the package?

Isn't anyone following up on this? I think I should turn this discussion into issue

**Comment by VladislavAntonyuk** [comment]
the solution for the issue:
```
- task: PowerShell@2
            displayName: 'Build Extension'
            inputs:
              targetType: 'inline'
              script: |
                dotnet publish 'src/BrowserExtensions/Chromium/BrowserExtension.csproj' --configuration $(buildConfiguration) --no-restore -p:Version="$(MajorVersion).$(MinorVersion).$(Build.BuildId)"
              pwsh: true

          - task: PowerShell@2
            displayName: 'Delete .gz files from Chromium extension'
            inputs:
              targetType: 'inline'
              script: |
                Get-ChildItem 'src/BrowserExtensions/Chromium/bin/$(buildConfiguration)/net8.0/browserextension/' -Recurse | Where{$_.Name -Match ".gz"} | Remove-Item
              pwsh: true

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: 'src/BrowserExtensions/Chromium/bin/$(buildConfiguration)/net8.0/browserextension/'
              archiveType: 'zip' 
              archiveFile: 'browserextension.zip'

          - task: PowerShell@2
            displayName: 'Copy extension to artifacts'
            inputs:
              targetType: 'inline'
              script: |
                Copy-Item "browserextension.zip" -Destination "$(Build.ArtifactStagingDirectory)" -Force
              pwsh: true

          - task: PublishBuildArtifacts@1
            inputs:
              ArtifactName: 'BrowserExtensions-$(Build.SourceBranchName)-$(Build.DefinitionVersion)'

          - powershell: |
                npm install --save-dev @plasmo-corp/ewu
                node upload.mjs ${env:PRODUCTID} ${env:CLIENTID} ${env:CLIENTSECRET} ${env:ACCESSTOKENURL}
            displayName: 'Publish extension to store'
            env:
              PRODUCTID: $(PRODUCTID)
              CLIENTID: $(CLIENTID)
              CLIENTSECRET: $(CLIENTSECRET)
              ACCESSTOKENURL: $(ACCESSTOKENURL)
```

So simple steps:
1. Build project
2. Delete all *.gz files (or any other archive files)
3. zip the directory
4. Upload it to the store
