### ISSUE TITLE
[Bug - Partner Center]  API upload results in 404

### ISSUE THREAD

**Issue by adamlui** [microsoft/MicrosoftEdge-Extensions#270]
**Describe the bug**
API upload results in 404

**To Reproduce**
1. Use an Action like [wdzeng/edge-addon](https://github.com/wdzeng/edge-addon) in a workflow like https://github.com/adamlui/chatgpt-auto-continue/blob/main/.github/workflows/publish-to-cws-ews-on-chromium-bump.yml:

```yml
...
      - name: Publish to EWS
        if: env.VERSION_CHANGED == 'true'
        uses: wdzeng/edge-addon@d4db1eea77297a24d799394dec87e8912e0902f9 # v2.1.0
        with:
          product-id: ${{ secrets.EWS_PRODUCT_ID }}
          client-id: ${{ secrets.EWS_CLIENT_ID }}
          api-key: ${{ secrets.EWS_CLIENT_SECRET }}
          zip-path: extension.zip
        continue-on-error: true
...
```

2. Trigger workflow via `on` condition

**Expected behavior**
API successfully uploads/publishes as per usual

**Screenshots**

https://github.com/adamlui/chatgpt-auto-continue/actions/runs/13259521783/job/37012713564

![Image](https://github.com/user-attachments/assets/1b880748-0f8d-4fea-a0ad-2a9e3cf22ec5)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser [e.g. chrome, safari]: N/A
 - Version [e.g. 22]: N/A

**Additional context**
- 500 error is reported in https://github.com/wdzeng/edge-addon/issues/16
- Irrecoverable failure is reported in https://github.com/microsoft/MicrosoftEdge-Extensions/issues/266
- Cause may be related
